name: CI Backend
on:
  pull_request:
    branches: ['**']
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [14.17.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --silent
      - name: Install dependencies
        run: npm install -g ganache-cli truffle standard install-peerdeps --silent
      - name: Run linter
        run: npm run solhint
      - name: Run Truffle tests
        run: truffle test
